//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GruppFemWCF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GruppFemdbEntities : DbContext
    {
        public GruppFemdbEntities()
            : base("name=GruppFemdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Establishment> Establishment { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserRating> UserRating { get; set; }
    }
}
