//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GruppFemWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRating
    {
        public int UserID { get; set; }
        public int EstablishmentID { get; set; }
        public double Rating { get; set; }
    
        public virtual Establishment Establishment { get; set; }
        public virtual User User { get; set; }
    }
}
